name: android-apk
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Show env (debug)
        run: |
          uname -a
          docker --version
          python3 --version
          ls -la

      - name: Cache Buildozer/Gradle
        uses: actions/cache@v4
        with:
          path: |
            .buildozer
            $HOME/.gradle/caches
            $HOME/.gradle/wrapper
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: buildozer-${{ runner.os }}-

      - name: Build with Buildozer (Docker)
        uses: addnab/docker-run-action@v3
        with:
          image: kivy/buildozer:latest
          options: -v ${{ github.workspace }}:/home/user/app -w /home/user/app
          run: |
            set -e
            export BUILDOZER_WARN_ON_ROOT=1
            buildozer --version
            buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
